version: "3.9"

services:
  api-gateway:
    build: api-gateway/
    ports:
      - "3000:3000"

  orders-service:
    build: orders-service/
    ports:
      - "4000:4000"

  products-service:
    build: products-service/
    ports:
      - "5000:5000"

  user-service:
    build: user-service/
    ports:
      - "6000:6000"